### ISSUE TITLE
WABT for generating binaries

### ISSUE THREAD

**Issue by tshort** [MikeInnes/Charlotte.jl#11]
Now that there's a BinaryBuilder for [WABT](https://github.com/WebAssembly/wabt) at [WABTBuilder](https://github.com/tshort/WABTBuilder/releases). That includes `bin/wast2wasm`, and it is compatible with Charlotte's wat/wast output.

Should I submit a PR to use that in Charlotte?

Eventually, we won't need this if someone codes up binary export to wasm.

**Comment by MikeInnes** [comment]
Yeah, as long as it works on a range of platforms I think it makes sense to make this convenient.

**Comment by tshort** [comment]
This was pretty easy. I added it to WebAssembly as that's where it made the most sense. It builds on top of the `invoke` branch, so I'll wait until that is merged to PR it. I'll close this as it doesn't really affect Charlotte. The only Charlotte-specific item is that we might want to re-export the WebAssembly function that writes to a wasm file.
